### ISSUE TITLE
How to prefetch properly - README Enhancement

### ISSUE THREAD

**Issue by mRs-** [pinterest/PINRemoteImage#115]
I'm using PINRemoteImage as my main image downloader and it's really awesome to use it. In my applications I use it as the main library for handling image downloads and prefetching them to store it locally on the disk. 

But I head to run through many obstacles to create a download task that is not cached in the memory cache but in the disk cache.

I would like to add more information about **How to prefetch properly** in the README file if it's ok with you guys. IMHO it's the best RemoteImage solution that we have in iOS OSS.

What is your opinion about this?

**Comment by garrettmoon** [comment]
That would be *super* awesome and greatly appreciated! If you have any swift examples you'd like to add that'd also be a welcome addition!

**Comment by danielgalasko** [comment]
I actually built an image preloading component ontop of PINRemoteImage and have been thinking about writing a Medium post about it. I ended up going around `PINRemoteImageManager.prefetchImagesWithURLs` because it doesn't return the UUIDs of any created operations. Ideally you want the flexibility of cancelling those requests as well.

The trick with preloading is that you need to store the URLs and update the preload window cursor as the user scrolls your list.

I had an ImagePreloader class that just maintained an array of URLs and had a single call to preload with a given cursor. The trick is to maintain a list of all known UUIDs so that you can cancel when needed
```
    /**
     * Preloads image downloads using a low priority queue.
     * The cursor is typically the indexPath.row property and uses the
     * internal `imageURLS` Array and looks ahead from the cursor to preload.
     */
    final func preloadImagesIfPossible(currentCursor: Int = 0) {
        performSerialOp(type: .Preload) {
            self.currentCursor = max(0,min(currentCursor, self.imageURLS.count - 1))
            let preloadWindowEndIndex = min(self.currentCursor + self.preloadWindowSize, self.imageURLS.count)
            if preloadWindowEndIndex > self.currentCursor {
                let urlsToPreload = Array(self.imageURLS[self.currentCursor..<preloadWindowEndIndex])
                for url in urlsToPreload {
                    if let uuid = PINRemoteImageManager.sharedImageManager().downloadImageWithURL(url, completion: nil) {
                        PINRemoteImageManager.sharedImageManager().setPriority(.Low, ofTaskWithUUID: uuid)
                        self.appendUUID(uuid)
                    }
                }
            }
        }
    }
```

Cancelling is easily achieved via

```
    func cancelAllDownloads() {
        performSerialOp(type: .CancelDownloads) {
            for uuid in self.imageUUIDs {
                PINRemoteImageManager.sharedImageManager().cancelTaskWithUUID(uuid)
            }
            self.imageUUIDs.removeAll()
        }
    }
```

**Comment by danielgalasko** [comment]
@mRs- not sure how your PR addresses preloading? Looks like you added stuff for progressive images?

**Comment by garrettmoon** [comment]
I'm going to close this out, feel free to put up PRs to improve documentation, they're greatly appreciated!
