### ISSUE TITLE
Question: Progressive JPEG vs WebP vs URLs of varying quality

### ISSUE THREAD

**Issue by oferRounds** [pinterest/PINRemoteImage#209]
Hi
First of all - thanks for this really really amazing library!

I'd like to ask a question please:
In my app most of image are ones which are uploaded by the client - via the users themselves.
I would like to use one of options which are supported by this library for combatting slow connections.

My question relates to the fact that I'm not sure which of the 3 options would work out best for me.
I searched on Google, but could not find a good compression of all 3.

Would love if someone would be able to explain the advantages & disadvantages of each method.

Thanks!

**Comment by garrettmoon** [comment]
WebP is more expensive to decode on device because there's no dedicated hardware. I think WebP may have a progressive option, but PINRemoteImage doesn't support it. Smaller download than JPEG, but bigger on device cost. Choosing this over JPEG depends on the network conditions of your users and the types of device they predominantly use.

Progressive JPEG is pretty awesome.

URLs of varying quality could be used in conjunction with progressive JPEGs. The idea behind it is to download a different version depending on network conditions. You'd still benefit from progressive.

**Comment by oferRounds** [comment]
@garrettmoon - thanks for your detailed answer!

One last question - does every JPEG supports Progressive, or when I decode and upload the image it should already be done for that purpose (i.e., in the way which supports it)?

**Comment by garrettmoon** [comment]
@oferRounds not every JPEG supports progressive, it depends on how it's encoded.

**Comment by oferRounds** [comment]
Got you - thanks again!
