### ISSUE TITLE
Question: checking if image exists in cache

### ISSUE THREAD

**Issue by oferRounds** [pinterest/PINRemoteImage#210]
When downloading an image and presenting it via a `UIImageView` instance, if image is not available on cache, I'd like to show an `Activity Indicator`.

I would like not to present the indicator if image is already available, so I want to check this before starting to present the indicator.

My questions are:

- Is this the right way to do it?

```
NSString *cacheKey = [[PINRemoteImageManager sharedImageManager] cacheKeyForURL:URL processorKey:nil];

UIImage *image = [[[PINRemoteImageManager sharedImageManager] defaultImageCache] objectForKey:cacheKey];

if (image) {
   ...
}
```

-  If so, is doing that will cause the image to get decoded on the main thread, thus affecting performance?

**Comment by maicki** [comment]
@oferRounds I don't know if this newly added API for `PINCache` is already available within `PINRemoteImage`, but instead of using `objectForKey:` on the cache you can use `containsObjectForKey:`. So it would look like:

```objc
NSString *cacheKey = [[PINRemoteImageManager sharedImageManager] cacheKeyForURL:URL processorKey:nil];
BOOL imageAvailable = [[[PINRemoteImageManager sharedImageManager] cache] containsObjectForKey:cacheKey];
```

`containsObjectForKey` does not decode any image it is just checking if the image is available on the disk. That said this is happening synchronously there is also an asynchronous variant: `containsObjectForKey:block:`

**Comment by oferRounds** [comment]
@maicki - that's a good idea, thanks a lot for replying!

**Comment by garrettmoon** [comment]
Another trick: PINRemoteImageManage will return nil from it's methods (instead of an operation NSUUID) when it retrieves the image from the memory cache. While it won't return nil when returning it from the disk cache, this would at least allow you to avoid showing it for the disk cache.

Gonna close this issue, feel free to reply back if you think if you'd like to work on adding more robust support and submit a PR :)

**Comment by oferRounds** [comment]
@garrettmoon - thanks for this one also! I'll look into submitting a PR :)
