### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by AndrewSB** [pinterest/PINRemoteImage#244]
Hey! 

I was wondering if pinterest already had established a timeline to upgrade this library to Swift 3?

**Comment by appleguy** [comment]
It’s not currently scheduled, just because we weren’t aware of the types of changes required to support it.  At the moment the maintainers aren’t using Swift, although we care a lot about ensuring there are no blockers to smooth & elegant usage in Swift.

If you could summarize what types of changes are required to achieve this, that would be helpful - and we’d be very interested in expediting the merge of any PRs you may come up with before we have a chance.

**Comment by AndrewSB** [comment]
I made this before testing! I mistakenly assumed the library wouldn't work with swift 3 😄
