### ISSUE TITLE
Question: identify two cached images as same image, just with different sizes

### ISSUE THREAD

**Issue by oferRounds** [pinterest/PINRemoteImage#247]
Hi

in my app, I have this common scenario: same image may presented in different sizes (say for example, that in screen A it is presented in a view which is 200x200 points, and on B - 50x50 points).

Now, my server API expose a mechanism (via the URL's GET parameters) which allows the client to ask for an image in a specific size. 

My question is then the following:
Lets say that screen A appeared before B, and after the client asked to get this image in 200x200 points, the image was fetched and cached. Now, when screen B appears, I'd like the client NOT to refetch the image on 50x50 points, but to use the one which it already has - the 200x200 points.

Alternatively, if screen B appeared first and the 50x50 image was fetched and cached, and then screen A appeared and the 200x200 image was also fetched and cached, I'd like the 50x50 to be cleared from the cache as the 200x200 can be used for both views.

Does this make sense? If so, how can I achieve it?

I'd love for help!
Thanks a lot!

**Comment by appleguy** [comment]
Great question, Ofer.  I think PINRemoteImage may be capable of this, but I don't know a definitive answer - @garrettmoon would.

If you are also using AsyncDisplayKit, note that ASMultiplexImageNode was designed for this behavior and should be able to do what you want.  It even scales the image representations it uses during animations, with automatic asynchronous fetching and decoding of the best-locally-available size while seeking the best-remote-available size.

		-- Scott

**Comment by garrettmoon** [comment]
@oferRounds I believe `downloadImageWithURLs:(nonnull NSArray <NSURL *> *)urls
                                   options:(PINRemoteImageManagerDownloadOptions)options
                             progressImage:(nullable PINRemoteImageManagerImageCompletion)progressImage
                                completion:(nullable PINRemoteImageManagerImageCompletion)completion;`

will do nearly what you want. You can pass in multiple URLs of increasing quality and it will download one based on the how fast previous images have downloaded. However, if one of the images has already been downloaded, it will use that one. It will also clear out the cache of images which are of lesser quality that have been downloaded, if a higher quality image is downloaded. Finally, you can set `shouldUpgradeLowQualityImages` to tell the system to download higher quality images if the connection improves.

So in your example above, screen b could use `downloadImageWithURLs:` and pass in lowQuality, highQuality and screen a could use the standard `downloadImageWithURL:` and pass in highQuality.

This won't do exactly what you want: screen b will download the higher quality version of the image instead of the lower quality version if the user's connection speed is fast. *and* if you want the lower quality version cleared out you'll manually need to do it on screen a because `downloadImageWithURL:` won't do it, only `downloadImageWithURLs:`

Hope this helps!

**Comment by oferRounds** [comment]
@appleguy - thank you (as always)! So that's another good reason for me to integrate AsyncDisplayKit!

@garrettmoon - thank you too! I'm actually now doing a work following your advice for a previous question I asked in the past - combining both Progressive JPEG and several URLs of varying quality. So I am about to use the method you mentioned.

Your suggestion sounds good for now. I'll start with this approach, and later switch to ASMultiplexImageNode. 

Beside it, if we speak here, I just wanted to say that I really enjoy using PINRemoteImage - it works really really great for me. Thank you for open sourcing this project!

**Comment by garrettmoon** [comment]
Thanks for the feedback! I'm always happy to hear when the project helps others :)

**Comment by oferRounds** [comment]
👍👍😊
