### ISSUE TITLE
Non-animated gif not recognized as such

### ISSUE THREAD

**Issue by tomizimobile** [pinterest/PINRemoteImage#274]
I ran into this issue using AsyncDisplayKit, and documented it here: https://github.com/facebook/AsyncDisplayKit/issues/2590#issuecomment-260467659

An image that shows this behavior is here: http://ak-cache.legacy.net/legacy/images/fhlogo/7630fhlogo.gif

**Comment by garrettmoon** [comment]
It looks like we should add a method pin_isAnimatedGIF which returns YES only if the data is a GIF *and* animated. We'd then need to check this instead of isGIF in most places.

**Comment by ArmandsB** [comment]
Is there any progress with this? Because GIPHY, which is one of largest gif provider (as can you see in image below), is using non-animated gifs as placeholder images, so there is a lot of blanks spaces in our application because of this (using Texture in our app).  

<img width="1283" alt="screen shot 2017-12-21 at 14 55 31" src="https://user-images.githubusercontent.com/3258393/34256720-5f5af846-e65f-11e7-83d7-9ff1610b26de.png">

**Comment by garrettmoon** [comment]
@ArmandsB sorry, no progress on this yet, but I'd happily accept a pull request!

**Comment by garrettmoon** [comment]
Had some extra time :)

**Comment by ArmandsB** [comment]
Sorry for long response (because of holidays), but everything works great! Thanks for fix 👍 

P.S Don't forget to include this fix also in Texture (ASPINRemoteImageDownloader class - alternateRepresentationWithData).
