### ISSUE TITLE
Understanding addImages method 

### ISSUE THREAD

**Issue by gnanaprakash** [pinterest/PINRemoteImage#33]
I'm new to iOS and likely going to use this library, trying to understand addImages method implementation, could see that add kitten object is added using main thread? why not directly add in it async block like mentioned below?

addImages {
                ....
                kitten.imageURL = kittenURLs[kittenIdx];
                kitten.imageSize = CGSizeMake(width / scale, height / scale);
                
//                dispatch_sync(dispatch_get_main_queue(), ^{
//                    [tmpKittens addObject:kitten];
//                });
                 [tmpKittens addObject:kitten];
}

**Comment by garrettmoon** [comment]
It's just out of laziness. If we do everything on one thread, the main thread in this case, we don't have to worry about thread safety. Otherwise we would have had to create some kind of thread synchronization method to make sure the asynchronous operations didn't happen at the same time and clobber tmpKittens.

**Comment by gnanaprakash** [comment]
Thanks Garrett. Got it.
