### ISSUE TITLE
[PINRemoteImageCategoryManager setImageOnView] Prevent view from being released.

### ISSUE THREAD

**Issue by tqtifnypmb** [pinterest/PINRemoteImage#465]
The view which call `setImageOnView` is captured by the `internalCompletion` block. This will avoid that view from being released. 

Is this a design choice ? What's this for ?

**Comment by garrettmoon** [comment]
It is captured, however it will still be released because PINRemoteImage releases blocks once the operation is completed. So essentially:
1. internalCompletion captures view.
2. PINRemoteImage fetches image and runs internalCompletion.
3. PINRemoteImage releases its strong hold on internalCompletion which frees the block.
4. The block releases its strong hold on the view.
5. Everyone is happy.

Please feel free to reply back if I'm missing something and thanks for bringing it up!

**Comment by tqtifnypmb** [comment]
It means the captured view can't be released until PINRemoteImage finish fetching image. 
Actually, I'm just curious about why PINRemoteImage do it this way.  :p

**Comment by garrettmoon** [comment]
It's not really necessary. If you want to open up a pull request to change it and use `PINWeakify` and `PINStrongify` I wouldn't be opposed to it. Might help clear up some memory in a few edge cases for people.
