### ISSUE TITLE
Dynamic imageView size only sets to the image size when scrolled

### ISSUE THREAD

**Issue by waseefakhtar** [pinterest/PINRemoteImage#480]
I'm trying to set my imageView height based on the image size when the image loads. Initially the height of my imageView is 0 but I notice that when I run the app, the images are set to a constant height and only sets the correct height for each image upon scroll. Here's how I set images in `cellForItemAt`:

```
imageView.pin_setImage(from: url, placeholderImage: nil, completion: { (result)  in
            guard let image = result.image else { return }
            
            let imageWidth: CGFloat = image.size.width
            let imageHeight: CGFloat = image.size.height
            let ratio =  imageWidth / imageHeight
            let newHeight = imageView.frame.width / ratio
            cell.imageConstraintHeight.constant = newHeight
        })
```

Before Scroll:

<img width="403" alt="screen shot 2018-09-23 at 7 35 31 pm" src="https://user-images.githubusercontent.com/4093820/45930369-e9cf1700-bf67-11e8-8651-069303b007a9.png">

After Scroll:

<img width="404" alt="screen shot 2018-09-23 at 7 31 41 pm" src="https://user-images.githubusercontent.com/4093820/45930324-5e558600-bf67-11e8-9388-377aa73392df.png">

Where do you think is the issue and how do you suggest I fix this?

**Comment by garrettmoon** [comment]
Hmm, I'm guessing this is an issue with auto layout… My hunch is that the constraints aren't being invalidated correctly when the image loads asynchronously (try to force relayout perhaps on image load?). When you scroll however, the cell is recreated and the image load block runs synchronously because it's being pulled from the cache, so the constraints are set correctly.

I would say that you may not like the experience of relying on getting the image size back from the image itself because even if you solve this issue the cells will resize every time an image is loaded asynchronously possibly jumping around the scroll position.

If it's possible to know the image size in advance that will be a better experience. At Pinterest, the API which returns the image URLs also returns the image sizes so we know the image size before layout.

**Comment by waseefakhtar** [comment]
That's correct. I agree, there are lots of details to get right before it runs smoothly. I've decided to rely on a fixed size for now but I'll try sometime to get the image size in advance like you suggest the API provides and let's see how things perform.

**Comment by garrettmoon** [comment]
Glad that will work. Going to close out this issue for now.
