### ISSUE TITLE
libwebp dependency is not Carthage compatible

### ISSUE THREAD

**Issue by addisonwebb** [pinterest/PINRemoteImage#487]
The `libwebp` dependency cannot be compiled by Carthage because it does not have a shared scheme.

```
*** Skipped building libwebp due to the error:
Dependency "libwebp" has no shared framework schemes
```

This prevents the use of `PINRemoteImage` since it depends on `libwebp`.

**Comment by garrettmoon** [comment]
Hey @addisonwebb would you mind uploading a sample project that demonstrates this?

**Comment by garrettmoon** [comment]
Hey @addisonwebb would you mind uploading a sample project that demonstrates this?

**Comment by addisonwebb** [comment]
Hi @garrettmoon. Here is a sample project that demos `libwebp` not building during the Carthage build process. Repro steps are in the README.

https://github.com/addisonwebb/PINRemoteImage-Issue487

There is a second branch that shows an Xcode project that successfully builds and runs with the `PINRemoteImage` dependency despite `libwebp` not building. I'm not sure what is different about the project I was working on the other day and this one but it doesn't seem to affect use of `PINRemoteImage`.

**Comment by garrettmoon** [comment]
Ok so I use Carthage infrequently and always forget how it works, but…

Essentially, PINRemoteImage is using Carthage to fetch and build its dependencies. But! because libwebp doesn't support Carthage itself, PINRemoteImage builds it in directly. So! It's safe to ignore the warning that webp isn't building, it'll still work (I plugged in a .webp image into the sample project on the `still-builds-despite-no-libwebp` branch and it worked).

So the warning is annoying, but I'm not sure of an easy way to get rid of it without retooling the build system to use GitHub submodules or something like that. Or for libwebp to support Carthage.

**Comment by garrettmoon** [comment]
And thank you for taking the time to make a sample project!

**Comment by addisonwebb** [comment]
Thanks for looking into this!

I just took a further look at how `libwebp` was integrated into the `PINRemoteImage` framework and I see that Carthage is being used only to checkout a specific version of `libwebp`. The files have been added to the project and is build with `PINRemoteCache` vs linking the framework built by Carthage. 

It all makes sense now. I think I was just thrown off because Carthage is being used here in a way that is probably not the intended use case.
