### ISSUE TITLE
Don't load image from cache

### ISSUE THREAD

**Issue by reinholdB** [pinterest/PINRemoteImage#56]
My server unfortunately returns the same image URL even if the picture is updated. Therefore I somehow need to skip the cache when loading an image. Could you please help me how this can be done?

I tried to clear the cache before loading the image:
```
 PINRemoteImageManager.sharedImageManager().defaultImageCache().removeAllObjects()
 profileImage.pin_cancelImageDownload()
            profileImage.pin_setImageFromURL(profileImageURL, placeholderImage: placeHolder) {
                (result:PINRemoteImageManagerResult!) in
            }

```
Nevertheless the image is returned from the cache.

**Comment by garrettmoon** [comment]
The call to profileImage.pin_cancelImageDownload() makes me suspicious.

Here's a situation that can happen with the above code.
Lets say you've called pin_setImageFromURL with a URL. Let's say it's not in the cache, so it goes off and downloads the image.

Now lets say you run the above code. Clearing the cache does nothing because the image isn't in there yet.

Then, you cancel the image download. Cancelling a download isn't guaranteed to happen synchronously, and therefore may or may not prevent the original download from completing and getting set in the cache.

Then, when you call pin_setImageFromURL again, lets say the image from the first call *has* finished downloading and now is in the cache. It will get returned.

If this is an issue for you, you could submit a PR for a synchronous version of cancelImageDownload.

**Comment by garrettmoon** [comment]
Hopefully this helps, feel free to re-open if this doesn't explain your issue.
