### ISSUE TITLE
GIF playback is slow/broken 

### ISSUE THREAD

**Issue by McsimumVelocity** [pinterest/PINRemoteImage#570]
GIFs are render extremely slowly in `3.0.1`. 

Here is the example GIF in the Swift Example app provided in the repo versus the same GIF loaded in Chrome: 

![slow_gif](https://user-images.githubusercontent.com/6392766/93920236-cda51280-fd06-11ea-85bb-5353e0ecb60a.gif)

This can be replicated with other GIFs also. 

Setup: 
- PINRemoteImage `3.0.1`
- Xcode 12 
- iPhone 11 Pro, iOS 14 simulator 

Any assistance would be greatly appreciated 🙏  Thanks.

**Comment by sridvijay** [comment]
I'm also running into the same issue :/ I've narrowed it down to a couple sections of code, but still am having trouble figuring out which part is wonky.

In `PINAnimatedImageView.m`, we have this snippet of code where the `frameInterval` is being set to 1 (hence the 1 update a second). If modified to the frame rate of your GIF (say 15 fps), everything seems to work fine again.

```
    // Get frame interval before holding display link lock to avoid deadlock
    NSUInteger frameInterval = self.animatedImage.frameInterval;

    if (_displayLink == nil) {
        _playHead = 0;
        _displayLink = [PINDisplayLink displayLinkWithTarget:[PINRemoteWeakProxy weakProxyWithTarget:self] selector:@selector(displayLinkFired:)];
#if PIN_TARGET_IOS
        if (@available(iOS 10.0, tvOS 10.0, *)) {
            _displayLink.preferredFramesPerSecond = frameInterval;
        } else {
#endif
            _displayLink.frameInterval = frameInterval;
#if PIN_TARGET_IOS
        }
#endif
```

That `frameInterval` is calculated in `PINAnimatedImage.m` here:
```
- (NSUInteger)frameInterval
{
    return MAX(self.minimumFrameInterval * [PINAnimatedImage maximumFramesPerSecond], 1);
}

//Credit to FLAnimatedImage ( https://github.com/Flipboard/FLAnimatedImage ) for display link interval calculations
- (NSTimeInterval)minimumFrameInterval
{
    static dispatch_once_t onceToken;
    static NSTimeInterval kGreatestCommonDivisorPrecision;
    dispatch_once(&onceToken, ^{
        kGreatestCommonDivisorPrecision = 2.0 / (1.0 / [PINAnimatedImage maximumFramesPerSecond]);
    });
    
    // Scales the frame delays by `kGreatestCommonDivisorPrecision`
    // then converts it to an UInteger for in order to calculate the GCD.
    NSUInteger scaledGCD = lrint([self durationAtIndex:0] * kGreatestCommonDivisorPrecision);
    for (NSUInteger durationIdx = 1; durationIdx < self.frameCount; durationIdx++) {
        CFTimeInterval duration = [self durationAtIndex:durationIdx];
        scaledGCD = gcd(lrint(duration * kGreatestCommonDivisorPrecision), scaledGCD);
    }
    
    // Reverse to scale to get the value back into seconds.
    return (scaledGCD / kGreatestCommonDivisorPrecision);
}
```

It seems like the `minimumFrameInterval` ends up being less than 1, and the MAX function returns 1. I played around with this but couldn't really understand the logic and which variable was wonky - `maximumFramesPerSecond` seems about right at 60, the `durationAtIndex` seemed right as well...

I tried in Xcode 11.7 with a device on iOS 13 and weirdly enough its showing up on there too (when it didn't before) - not sure if its a conflict in cache between Xcode's or something.

Easy workaround for now though is using the `FLAnimatedImageView` that powers it directly with something like this:
```
    if let gifData = try? Data(contentsOf: url) {
       let animatedThumbnail = FLAnimatedImage(animatedGIFData: gifData)
       self.animatedImageView.animatedImage = animatedThumbnail
       self.animatedImageView.startAnimating()
    }
```

Would love to understand what the root cause of this is though - hope someone with better debug skills than me can find out!

**Comment by bdolman** [comment]
@sridvijay Thanks for your comment -- it pointed me in the right direction. Would love it if you could verify my PR that I think should fix this: https://github.com/pinterest/PINRemoteImage/pull/572

**Comment by McsimumVelocity** [comment]
Thanks so much for this fix @bdolman and @sridvijay. Any ETA on a release that will include this? We have a dependency on it in one of our own pods. It's causing us some difficulties. Would be really helpful for our own planning to have a rough release time.
