### ISSUE TITLE
Use NS_EXTENSION_UNAVAILABLE_IOS instead of PIN_APP_EXTENSIONS

### ISSUE THREAD

**Issue by jparise** [pinterest/PINRemoteImage#93]
`NS_EXTENSION_UNAVAILABLE_IOS` can be used to mark symbols as unavailable to extensions. This should allow us to remove the `PIN_APP_EXTENSIONS` define and produce one library for both application and extensions.

Inspired by AFNetworking/AFNetworking#2737. Depends on pinterest/PINCache#37.

**Comment by mRs-** [comment]
I created a pull request for this with the changes. Am I doing it right?

**Comment by garrettmoon** [comment]
I actually think this was done incorrectly, the macro is meant to *mark* api's as unavailable to extensions. I think I need to revert the commit and investigate if this is even possible.

**Comment by garrettmoon** [comment]
From my understanding, NS_EXTENSION_UNAVAILABLE_IOS will only allow us to mark methods as unavailable for use in extensions, it *won't* allow us to compile separate code paths. So I'm not sure it will actually add value? :(

**Comment by mRs-** [comment]
From the documentation
`Use any API marked in header files with the NS_EXTENSION_UNAVAILABLE macro, or similar unavailability macro, or any API in an unavailable framework `

So you can explicit flag a method as unavailable in an extension. I don't know if there is a real impact on the code paths.

**Idea**
1. Different APIs for extension / app, the one for the app marked as `NS_EXTENSION_UNAVAILABLE_IOS`
2. Same API and under the hood two private methods that are switching with `canPerformSelector` in the hope `NS_EXTENSION_UNAVAILABLE_IOS` is handling this way
3. revert the commit and go back to the good old `PIN_APP_EXTENSIONS`. IMHO it's so last favorite way because each pod is using a different name here :(

**Comment by ibireme** [comment]
Use this method to get `UIApplication`:

    /// Returns nil in App Extension.
	static UIApplication *_YYSharedApplication() {
	    static BOOL isAppExtension = NO;
	    static dispatch_once_t onceToken;
	    dispatch_once(&onceToken, ^{
	        Class cls = NSClassFromString(@"UIApplication");
	        if(!cls || ![cls respondsToSelector:@selector(sharedApplication)]) isAppExtension = YES;
	        if ([[[NSBundle mainBundle] bundlePath] hasSuffix:@".appex"]) isAppExtension = YES;
	    });
	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Wundeclared-selector"
	    return isAppExtension ? nil : [UIApplication performSelector:@selector(sharedApplication)];
	#pragma clang diagnostic pop
	}

and then use `NS_EXTENSION_UNAVAILABLE_IOS ` to mark the API.

See my example: https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYWebImageManager.m

**Comment by garrettmoon** [comment]
@mRs- 

1. Is possible, though I'd only be in support of this if it were only a *couple* of methods we could mark this way. I think we could possibly get away with it, but it wouldn't be very clean.

2. I don't think it works that way. I'm 90% sure that NS_EXTENSION_UNAVAILABLE_IOS is just an indicator to the compiler to mark a method as unavailable. I don't think it changes anything at runtime nor compiles anything differently.

3. I think this is our best option at the time. I'd be *very* supportive of getting rid of it, but I think the above solutions create more cost. I could be wrong though and would be happy to merge in something that isn't too complex and has been thoroughly tested.

**Comment by garrettmoon** [comment]
I'm going to close this for now as I don't think there's a good solution available.
